version: '3.9'

services:
  # Foundry node container
  # Binds lcoal source dir and docker daemon as volumes
  node:
    build:
      args:
        - SOLC_VERSION=0.8.12
      context: .
    container_name: frhtmlipfs_anvil
    entrypoint: ["anvil"]
    env_file:
      - '.env'
    network_mode: "host"
    # ports:
      # - "8545:8545"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  # Development environment container
  # Binds local source dir. docker daemon and git credential manager as volumes  
  dev:
    build:
      args:
        - SOLC_VERSION=0.8.12
      context: .
    container_name: frhtmlipfs_forge
    entrypoint: ["/docker/entrypoint.sh"]
    env_file:
      - '.env'
    network_mode: "host"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe:/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe

  echidna:
    build:
      context: ./echidna
    container_name: frhtmlipfs_echidna
    network_mode: "host"
    volumes:
      - .:/app

  # Container for running build and test 
  build:
    build:
      context: .
    container_name: frhtmlipfs_build
    entrypoint: ["forge", "build", "--via-ir"]
    env_file:
      - '.env'
    network_mode: "host"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe:/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe

  # Container for running build and test 
  test:
    build:
      context: .
    container_name: frhtmlipfs_test
    entrypoint: ["forge", "test", "--via-ir", "-vvvv"]
    env_file:
      - '.env'
    network_mode: "host"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe:/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe