coverage: false
# corpusDir: echidna-corpus
seqLen: 3
testLimit: 50000
shrinkLimit: 1000

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "ds-test/=lib/forge-std/lib/ds-test/src/ forge-std/=lib/forge-std/src/ @openzeppelin/=lib/openzeppelin-contracts/ @chainlink/=lib/chainlink/ base64-sol/=lib/base64/ ERC721A/=lib/ERC721A/contracts/",
  ]