[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
solc_version = '0.8.16'
memory_limit = 1533554432 # 1533.5mb

fuzz = { runs = 3_000 }
src = "test"

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ''

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config